---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: default # service是namespace下的资源
spec:
  selector: # Pod选择器 依照这个来代理不同的pods
    app: nginx
  type: ClusterIP # service的类型
  ports:
    - name: http 
      port: 80 # service的端口号
      targetPort: 80 # 对应到pod的端口号
      protocol: TCP # 还支持udp，http等